services:
  elasticsearch:
    image: elasticsearch:8.18.0
    container_name: ${APP_NAME}-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.18.0
    container_name: ${APP_NAME}-kibana
    environment:
      - ELASTICHSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  logstash:
    image: logstash:8.18.0
    container_name: ${APP_NAME}-logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/logs:ro

  jaeger:
    container_name: ${APP_NAME}-jaeger
    image: jaegertracing/all-in-one:1.68.0
    ports:
      - "16686:16686"

  prometheus:
    image: bitnami/prometheus:latest
    container_name: ${APP_NAME}-prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  grafana:
    container_name: ${APP_NAME}-grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/
      - ./grafana/dashboard:/etc/grafana/dashboard/
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:3.5
    container_name: ${APP_NAME}-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.5
    container_name: ${APP_NAME}-promtail
    volumes:
      - ./logs:/logs:ro
      - ./configs/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${APP_NAME}-app
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - logstash
      - kibana
      - jaeger
      - prometheus
      - grafana
      - loki
      - promtail

volumes:
  prometheus_data: {}
  grafana_data: {}
